# Generated by Django 3.2.12 on 2022-02-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=64)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
